#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME=vnt
PROG=/usr/bin/$NAME-cli

validate_section_vnt() {
	uci_load_validate "${NAME}" general "$1" "$2" \
		'enable:bool:0' \
		'conf_yaml:string'
}

uci_get_by_type() {
	local ret=$(uci get ${NAME}.@$1[0].$2 2>/dev/null)
	echo "${ret:=$3}"
}

gen_config_file() {
	local custom_config=$(uci_get_by_type general conf_yaml)
	[ ! "${#custom_config}" == "0" ] && echo "${custom_config}" > /var/etc/vnt/conf.yaml
	if [ echo "${custom_config}"|grep -q '^device_id' ]; then
	else
		echo 'device_id: 00000000-0000-0000-0000-'$(cat /sys/class/net/br-lan/address|tr -d ':') >> /var/etc/vnt/conf.yaml
	fi
}

vnt_instance() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	[ "${enable}" = 0 ] && return 1

	gen_config_file
	procd_open_instance "$1"
	procd_set_param command "$PROG"
	procd_append_param command -f /var/etc/vnt/conf.yaml

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

start_service() {
	mkdir -p /var/etc/vnt
	rm -f /var/etc/vnt/*
	config_load "${NAME}"
	config_foreach validate_section_vnt general vnt_instance
}

reload_service() {
	stop
	start
}
